apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: choustoulakis-cms-app
resources:
  - configmap.yaml
  - service.yaml
  - deployment.yaml
namespace: choustoulakis

secretGenerator:
  - files:
      - application.properties=secrets/application.properties
    name: choustoulakis-cms-secret
