name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn clean package
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Login to Amazon ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h7v4k5t3
    - name: build image
      run: docker build . -t choustoulakis-cms
    - name: tag image
      run: docker tag choustoulakis-cms:latest public.ecr.aws/h7v4k5t3/choustoulakis-cms:$(git rev-parse --short "$GITHUB_SHA")
    - name: push to ecr
      run: docker push public.ecr.aws/h7v4k5t3/choustoulakis-cms:$(git rev-parse --short "$GITHUB_SHA")

